# Generated by Django 5.0.7 on 2024-10-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='support@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_number',
            field=models.CharField(default='1234567890', max_length=255),
        ),
    ]
