# Generated by Django 5.1.1 on 2024-11-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_productimage_delete_productmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='store_tag',
            field=models.CharField(default='Elevating your style with grace and sophistication.', max_length=255),
        ),
    ]
