# Generated by Django 5.1.1 on 2026-04-09 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintoken',
            name='token_hash',
        ),
        migrations.AddField(
            model_name='admintoken',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, help_text='Your login token. Auto-generated if left blank. You can set a custom one — minimum 10 characters, must include at least one uppercase letter, one lowercase letter, and one digit. Example of a strong custom token: MyShop2024x', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admintoken',
            name='label',
            field=models.CharField(blank=True, help_text="Optional label to identify this token (e.g. 'office-laptop').", max_length=100),
        ),
    ]
