# Generated by Django 5.1.1 on 2026-04-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_admintoken_token_hash_admintoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintoken',
            name='token',
            field=models.CharField(blank=True, help_text='Your login token. Auto-generated if left blank. You can set a custom one — minimum 10 characters, must include at least one uppercase letter, one lowercase letter, and one digit. Example of a strong custom token: MyShop2024x', max_length=100, null=True, unique=True),
        ),
    ]
