# Generated by Django 5.1.1 on 2026-04-10 23:34

import core.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_admintoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_methods',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list, e.g. "Pickup, Home Delivery"', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_note',
            field=models.CharField(blank=True, default='', help_text='Optional short note shown to customers during checkout', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_time',
            field=models.CharField(blank=True, default='', help_text='e.g. "2–5 business days"', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Optional note from the customer at checkout', max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.models.validate_image_size]),
        ),
    ]
